### PR TITLE
Using get_unaligned_le16 instead of packed structures

### PR DESCRIPTION
**Pull request by barni2000**
I found a TODO in the code. I did it.

### CODE REVIEW

**Comment by onitake** [comment]
Wow, thank you. The TODO comment was more of a note to self, not something I actually planned to do. `get_unaligned_*` is definitely more portable, but less readable than packed structs.

I think `get_unaligned_le16` does the byteswapping automatically, no need to `le16_to_cpu` afterwards. [See here](https://lwn.net/Articles/277779/).

**Comment by gsantner** [comment]
is this still WIP or not needed anymore?

**Comment by onitake** [comment]
Sorry, this got bogged down.
I'll review and merge it ASAP.

**Comment by gsantner** [comment]
(Y)

**Comment by jabjoe** [comment]
This looks ok, this all worked last time I checked. But I've not even looked at this code in a long time and you have so... I'll just merge. :-)

**Comment by onitake** [comment]
I've actually abandoned gslx680-acpi in the meantime, as there's a better driver in the Linux kernel now. It supports both ARM/DeviceTree and x86/ACPI.
I guess there's not too much harm in merging this now. I'll look it over and merge it.

**Pull request closed without merging**
